{{- if .Values.blueprints.enabled }}
{{- $redisUrl := coalesce .Values.blueprints.secret.redisUrl (ternary (printf "redis://%s-blueprints-redis:6379/0" (include "codearmory.fullname" .)) "" .Values.blueprints.redis.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-blueprints
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: blueprints
type: Opaque
stringData:
{{- if .Values.blueprints.secret.databaseUrl }}
  database-url: {{ .Values.blueprints.secret.databaseUrl | quote }}
{{- end }}
  redis-url: {{ $redisUrl | quote }}
  encryption-key: {{ .Values.blueprints.secret.encryptionKey | quote }}
  gatekeeper-service-key: {{ .Values.blueprints.secret.gatekeeperServiceKey | quote }}
{{- end }}
