{{- if and .Values.chaos.enabled .Values.chaos.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-chaos
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: chaos
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.chaos.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: chaos
{{- end }}
