apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-conductor
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: conductor
type: Opaque
stringData:
  registry-read-key: {{ .Values.conductor.secret.registryReadKey | quote }}
  conductor-forward-key: {{ .Values.conductor.secret.conductorForwardKey | quote }}
