{{- if .Values.containers.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-containers
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: containers
type: Opaque
stringData:
  registry-url: {{ .Values.containers.secret.registryUrl | quote }}
  registry-username: {{ .Values.containers.secret.registryUsername | quote }}
  registry-password: {{ .Values.containers.secret.registryPassword | quote }}
  gatekeeper-service-key: {{ .Values.containers.secret.gatekeeperServiceKey | quote }}
{{- end }}
