{{- if and .Values.forge.enabled .Values.forge.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "codearmory.forge.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: forge
  {{- with .Values.forge.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
