{{- $redisUrl := coalesce .Values.gatekeeper.secret.redisUrl (ternary (printf "redis://%s-gatekeeper-redis:6379/0" (include "codearmory.fullname" .)) "" .Values.gatekeeper.redis.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-gatekeeper
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: gatekeeper
type: Opaque
stringData:
{{- if .Values.gatekeeper.secret.databaseUrl }}
  database-url: {{ .Values.gatekeeper.secret.databaseUrl | quote }}
{{- end }}
  redis-url: {{ $redisUrl | quote }}
  gatekeeper-services: {{ .Values.gatekeeper.secret.gatekeeperServices | quote }}
  registry-service-key: {{ .Values.gatekeeper.secret.registryServiceKey | quote }}
{{- if .Values.gatekeeper.secret.oidcSigningKey }}
  oidc-signing-key: {{ .Values.gatekeeper.secret.oidcSigningKey | quote }}
{{- end }}
