{{- if .Values.gitFactory.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-git-factory
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: git-factory
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gitFactory.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: git-factory
{{- end }}
