{{- if .Values.giteaIntegration.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-gitea-integration
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: gitea-integration
type: Opaque
stringData:
{{- if .Values.giteaIntegration.secret.databaseUrl }}
  database-url: {{ .Values.giteaIntegration.secret.databaseUrl | quote }}
{{- end }}
  gitea-url: {{ .Values.giteaIntegration.secret.giteaUrl | quote }}
  gitea-admin-token: {{ .Values.giteaIntegration.secret.giteaAdminToken | quote }}
  gatekeeper-service-key: {{ .Values.giteaIntegration.secret.gatekeeperServiceKey | quote }}
{{- end }}
