{{- if .Values.hooks.enabled }}
{{- $dbUrl := coalesce .Values.hooks.secret.databaseUrl (ternary (include "codearmory.postgresql.dsn" (list . "hooks")) "" .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-hooks
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: hooks
type: Opaque
stringData:
  database-url: {{ $dbUrl | quote }}
  gatekeeper-service-key: {{ .Values.hooks.secret.gatekeeperServiceKey | quote }}
  hooks-trigger-key: {{ .Values.hooks.secret.hooksTriggerKey | quote }}
{{- end }}
