{{- if .Values.hooks.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-hooks
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: hooks
type: Opaque
stringData:
{{- if .Values.hooks.secret.databaseUrl }}
  database-url: {{ .Values.hooks.secret.databaseUrl | quote }}
{{- end }}
  gatekeeper-service-key: {{ .Values.hooks.secret.gatekeeperServiceKey | quote }}
  hooks-trigger-key: {{ .Values.hooks.secret.hooksTriggerKey | quote }}
{{- end }}
