{{- if and .Values.outpostGateway.enabled .Values.outpostGateway.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-outpost-gateway
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: outpost-gateway
spec:
  type: {{ .Values.outpostGateway.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.outpostGateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: outpost-gateway
{{- end }}
