apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-portal
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  type: {{ .Values.portal.service.type }}
  ports:
    - port: {{ .Values.portal.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: portal
