{{- $dbUrl := coalesce .Values.registry.secret.databaseUrl (ternary (include "codearmory.postgresql.dsn" (list . "registry")) "" .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-registry
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
type: Opaque
stringData:
  database-url: {{ $dbUrl | quote }}
  admin-key: {{ .Values.registry.secret.adminKey | quote }}
  read-key: {{ .Values.registry.secret.readKey | quote }}
