apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-registry
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.registry.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: registry
