{{- if and .Values.tickets.enabled .Values.tickets.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-tickets
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: tickets
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tickets.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tickets
{{- end }}
