{{- if .Values.tickets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-tickets
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: tickets
type: Opaque
stringData:
{{- if .Values.tickets.secret.databaseUrl }}
  database-url: {{ .Values.tickets.secret.databaseUrl | quote }}
{{- end }}
  gatekeeper-service-key: {{ .Values.tickets.secret.gatekeeperServiceKey | quote }}
{{- end }}
