{{- if .Values.tickets.enabled }}
{{- $dbUrl := coalesce .Values.tickets.secret.databaseUrl (ternary (include "codearmory.postgresql.dsn" (list . "tickets")) "" .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-tickets
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: tickets
type: Opaque
stringData:
  database-url: {{ $dbUrl | quote }}
  gatekeeper-service-key: {{ .Values.tickets.secret.gatekeeperServiceKey | quote }}
{{- end }}
