{{- if .Values.workflows.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codearmory.fullname" . }}-workflows
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: workflows
type: Opaque
stringData:
{{- if .Values.workflows.secret.databaseUrl }}
  database-url: {{ .Values.workflows.secret.databaseUrl | quote }}
{{- end }}
  gatekeeper-service-key: {{ .Values.workflows.secret.gatekeeperServiceKey | quote }}
  hooks-trigger-key: {{ .Values.workflows.secret.hooksTriggerKey | quote }}
  token-key: {{ .Values.workflows.secret.tokenKey | quote }}
{{- end }}
