{{- if and .Values.workflows.enabled .Values.workflows.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "codearmory.fullname" . }}-workflows
  labels:
    {{- include "codearmory.labels" . | nindent 4 }}
    app.kubernetes.io/component: workflows
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.workflows.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "codearmory.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: workflows
{{- end }}
