package main

import "time"

// The wiki is a project's living source of truth: the architect writes it, the dev
// and review stages read it. It is NOT stored in this service — the content lives in a
// git repository reached through a Store (git-factory today, the git connector's other
// backends later), so history and diffs are git's, not ours. This file defines the
// schema the service layers ON TOP of that git repo: the fixed page types and the
// machine-readable manifest that makes reads scopeable.

const maxBodyBytes = 1 << 20 // 1 MiB — a wiki page (prose or a schema file) is small

// PageType is the closed set of page kinds. A closed set (not free-form) is what lets a
// dev agent ask for "the API contract" and get exactly one known thing.
type PageType string

const (
	TypeOverview     PageType = "overview"     // what/why/scope
	TypeArchitecture PageType = "architecture" // services, boundaries, data flow
	TypeContract     PageType = "contract"     // an API/event contract — the fan-out artifact
	TypeModel        PageType = "model"        // data model / shared types
	TypeService      PageType = "service"      // one deployable unit (feeds devops)
	TypeComponent    PageType = "component"    // a frontend page/component
	TypeDecision     PageType = "decision"     // an ADR (append-only by convention)
	TypeTicket       PageType = "ticket"       // per-ticket context, generated by the architect
)

func (t PageType) valid() bool {
	switch t {
	case TypeOverview, TypeArchitecture, TypeContract, TypeModel, TypeService, TypeComponent, TypeDecision, TypeTicket:
		return true
	}
	return false
}

// Stack says who owns/consumes a page, so a ticket can pull only its lane's pages.
type Stack string

const (
	StackShared   Stack = "shared"
	StackFrontend Stack = "frontend"
	StackBackend  Stack = "backend"
	StackInfra    Stack = "infra"
)

func (s Stack) valid() bool {
	switch s {
	case StackShared, StackFrontend, StackBackend, StackInfra, "":
		return true
	}
	return false
}

// PageMeta is one manifest entry: everything about a page EXCEPT its body. The manifest
// is the machine index an agent reads to resolve a page id to its path/kind without
// cloning the whole wiki.
type PageMeta struct {
	ID        string    `json:"id"`              // stable slug, e.g. "contract-api"
	Path      string    `json:"path"`            // file path in the repo, e.g. "contracts/api.openapi.yaml"
	Type      PageType  `json:"type"`            //
	Stack     Stack     `json:"stack,omitempty"` //
	Format    string    `json:"format"`          // md | openapi | sql | ts | yaml
	Title     string    `json:"title"`           //
	Status    string    `json:"status"`          // draft | approved | superseded
	Version   int       `json:"version"`         // bumped per write; git holds the real history
	Related   []string  `json:"related,omitempty"`
	Updated   time.Time `json:"updated_at"`
	UpdatedBy string    `json:"updated_by,omitempty"`
}

// Manifest is the authoritative index of a project's wiki, stored at manifestPath in the
// repo. The service keeps it in step with the page files on every write.
type Manifest struct {
	Project    string     `json:"project"`
	Pages      []PageMeta `json:"pages"`
	VersionTag string     `json:"version_tag,omitempty"` // the pinnable baseline for drift checks
	Updated    time.Time  `json:"updated_at"`
}

// Page is a manifest entry plus its body — the full read/write unit of the API.
type Page struct {
	PageMeta
	Content string `json:"content"`
}

// manifestPath is where the index lives in the repo. Under .wiki/ so it sits beside, not
// inside, the human-facing page tree.
const manifestPath = ".wiki/manifest.json"

// Commit is one history entry for a page, surfaced verbatim from git-factory's log.
type Commit struct {
	SHA     string    `json:"sha"`
	Subject string    `json:"subject"`
	Author  string    `json:"author,omitempty"`
	Date    time.Time `json:"date"`
}

type putPageRequest struct {
	Type    PageType `json:"type"`
	Stack   Stack    `json:"stack"`
	Format  string   `json:"format"`
	Title   string   `json:"title"`
	Status  string   `json:"status"`
	Content string   `json:"content"`
	Related []string `json:"related"`
	Path    string   `json:"path"` // optional; defaulted from type+id+format when empty
}
