{{- if and (not .Values.existingSecret) .Values.enrollmentToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outpost.fullname" . }}-enrollment
  labels:
    {{- include "outpost.labels" . | nindent 4 }}
type: Opaque
stringData:
  enrollment-token: {{ .Values.enrollmentToken | quote }}
{{- end }}
