name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"
      - name: Run gatekeeper unit tests
        run: cd src/systems/gatekeeeper; go test .
      - name: Run blueprints unit tests
        run: cd src/systems/blueprints; go test .
      - name: Run conductor unit tests
        run: cd src/systems/conductor; go test .
      - name: Run cli unit tests
        run: cd src/cli; go test .

  release:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      deployments: write
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
